import os

SERVICE_HOST = os.getenv('BOLLYDOG_WS_SERVICE_HOST', '0.0.0.0')
SERVICE_DEBUG = os.getenv('BOLLYDOG_WS_SERVICE_DEBUG', 'False') == 'True'
SERVICE_PORT = os.getenv('BOLLYDOG_WS_SERVICE_PORT', 8001)
SERVICE_LOG_LEVEL = os.getenv('BOLLYDOG_WS_SERVICE_LOG_LEVEL', 'info')
