# 与仓库根 config.yaml 一致
timing:
  app: !module timing.engine.app.TimingApp
  clock: !module timing.common.clock.LiveClock

backtest:
  app: !module timing.engine.app.BacktestApp
  clock: !module timing.common.clock.SimulatedClock
