import os

SERVICE_HOST = os.getenv('BOLLYDOG_HTTP_SERVICE_HOST', '0.0.0.0')
SERVICE_DEBUG = os.getenv('BOLLYDOG_HTTP_SERVICE_DEBUG', 'False') == 'True'
SERVICE_PORT = os.getenv('BOLLYDOG_HTTP_SERVICE_PORT', 8000)
SERVICE_LOG_LEVEL = os.getenv('BOLLYDOG_HTTP_SERVICE_LOG_LEVEL', 'info')

# SERVICE_SECRET_KEY = os.getenv('BOLLYDOG_HTTP_SERVICE_SECRET_KEY', 'KFC-CRAZY-THURSDAY-VME-50')

SERVICE_PRIVATE_KEY = os.getenv('BOLLYDOG_HTTP_SERVICE_PRIVATE_KEY', None)
SERVICE_PUBLIC_KEY = os.getenv('BOLLYDOG_HTTP_SERVICE_PUBLIC_KEY', None)
SERVICE_PRIVATE_KEY_PATH = os.getenv('BOLLYDOG_HTTP_SERVICE_PRIVATE_KEY_PATH', None)
SERVICE_PUBLIC_KEY_PATH = os.getenv('BOLLYDOG_HTTP_SERVICE_PUBLIC_KEY_PATH', None)

SERVICE_LOOP = os.getenv('BOLLYDOG_HTTP_SERVICE_LOOP', 'uvloop')
SERVICE_HTTP = os.getenv('BOLLYDOG_HTTP_SERVICE_HTTP', 'httptools')
SERVICE_LIMIT_CONCURRENCY = int(os.getenv('BOLLYDOG_HTTP_SERVICE_LIMIT_CONCURRENCY', 0)) or None
SERVICE_LIMIT_MAX_REQUESTS = int(os.getenv('BOLLYDOG_HTTP_SERVICE_LIMIT_MAX_REQUESTS', 2000))
SERVICE_TIMEOUT_KEEP_ALIVE = int(os.getenv('BOLLYDOG_HTTP_SERVICE_TIMEOUT_KEEP_ALIVE', 5))
SERVICE_BACKLOG = int(os.getenv('BOLLYDOG_HTTP_SERVICE_BACKLOG', 128))

# Middleware toggles (0=off, 1=on)
MIDDLEWARE_SESSION_ENABLED = os.getenv('BOLLYDOG_HTTP_MIDDLEWARE_SESSION', '1') == '1'
MIDDLEWARE_AUTH_ENABLED = os.getenv('BOLLYDOG_HTTP_MIDDLEWARE_AUTH', '1') == '1'
MIDDLEWARE_CORS_ENABLED = os.getenv('BOLLYDOG_HTTP_MIDDLEWARE_CORS', '1') == '1'
MIDDLEWARE_SESSION_SECRET_KEY = os.getenv('HTTP_MIDDLEWARE_SESSIONS_SECRET_KEY', '')
